# Generated by Django 3.1.1 on 2020-12-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Restaurant'),
        ),
        migrations.AlterField(
            model_name='openinghours',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='location',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Location'),
        ),
    ]
