# Generated by Django 2.1.5 on 2020-12-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201212_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_healthy',
            field=models.BooleanField(default=False),
        ),
    ]
