# Generated by Django 2.1.5 on 2020-12-16 20:27

import app.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201216_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='user_order',
        ),
        migrations.AddField(
            model_name='order',
            name='user_order',
            field=app.custom_fields.ListField(default="[['burger', '2'], ['pizza', '1']]", token=','),
            preserve_default=False,
        ),
    ]
