# Generated by Django 2.1.5 on 2020-12-16 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201216_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_ordered', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.MenuItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_order',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Order'),
        ),
    ]
